apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fj2qxpp22-java-quarkus-gitops
  description: This is GitOps manifest for fj2qxpp22-java-quarkus   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=fj2qxpp22-java-quarkus
    backstage.io/kubernetes-id: fj2qxpp22-java-quarkus 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fj2qxpp22-java-quarkus
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fj2qxpp22-java-quarkus
